name: First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6

        - name: List files
          run: ls

        - name: execute shell script
          run: 
            chmod +x my-script.sh
            ./my-script.sh
       
        