name: First workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6

        - name: Welcome message
          run:
             echo "My first github workflow command"
             ls
             cat index.html

        - name: install cowsay
          run: sudo apt install cowsay -y

        - name: Create bunny
          run: cowsay -f bunny "I live in jungle" >> bunny.txt

        - name: show bunny
          run: cat bunny.txt


        